### ISSUE TITLE
Invalid JSON in error responses

### ISSUE THREAD

**Issue by tvl83** [freewil/node-bitcoin#26]
`{ [Error: Invalid params, response status code: 403] code: -32602 }` is not a valid JSON object that I can parse and consume easily. 

When parsing the response it sees the code key and value but not the error message. I think it has something to do with using the `new Error()` in jsonrpc.js.

I was thinking of just creating an object myself on all these calls
```
var err = {
  error: "Invalid Params, response status code: 403",
  code: -32602
}
```

and return err the same way. Would this hurt anything. Is there a reason the error response is not valid json ?

**Comment by freewil** [comment]
This is standard behavior in Node. If there is an error, an Error object is passed as the first parameter to the callback function. Why do you need to convert the Error object to JSON? If you really need to do that you can just do `JSON.stringify(err)` - you also may want to see this [question about stringifying Error objects](https://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify)
