### ISSUE TITLE
Test network

### ISSUE THREAD

**Issue by daminufe** [freewil/node-bitcoin#28]
Hello, how can I connect to the test network in order to implement the api with a web project? To have fake bitcoins to test transactions?
Regards

**Comment by freewil** [comment]
You'll need to configure bitcoind to connect to either the public testnet or your own private testnet and configure node-bitcoin to connect to it's rpc server as normal. Check out [the testnet-box](https://github.com/freewil/bitcoin-testnet-box)

**Comment by daminufe** [comment]
Yes, I am using the public testnet, however I am getting an error. If using the live bitcoin, it works, with the testnet it doesn't.
![image](https://cloud.githubusercontent.com/assets/4832774/9130045/3c6716de-3cdf-11e5-9186-0109f8e030df.png)

**Comment by dcousens** [comment]
@daminufe I'm not fully aware of your environment,  but a testnet node will typically only bind to port `18333`,  compared to `8333` that a bitcoin node will use.
That *could* be your issue.

**Comment by Gamaroff** [comment]
I'm having the same problem on testnet.
@daminufe did you manage to solve this one?

**Comment by daminufe** [comment]
Yes, I found was a misconfiguration on my machine. It's fixed now.
