### ISSUE TITLE
Limit number of requests to bitcoin-core

### ISSUE THREAD

**Issue by MaxSchumacher** [freewil/node-bitcoin#30]
Hi everyone,

thanks for building this really helpful library.

I'm using it for a research project on transaction costs in Bitcoin and have to make a lot of requests to bitcoin core. 

At ~2 million requests (getting the blockhash, getting the block, getting each transaction and extracting the value of inputs to a transaction with another getttransaction call) causes some problems with limits imposed by the TCP sockets used to make the requests: 

Too many requests at a time and the system breaks down:  

connect EADDRNOTAVAIL 127.0.0.1:8332 - Local (127.0.0.1:0)

In bitcoin.conf I've turned the (parallel?) rpc threads to 200, in my node-bitcoin configuration I turned up the timeout to 100000.

What's a good way to spread out the requests made via node-bitcoin against bitcoin-core so the the system doesn't break? Could setTimeout work?

Greetings and all the best,
Max

**Comment by freewil** [comment]
I would take a look at one of the `xLimit` functions from the async library. Something like [`timesLimit`](https://github.com/caolan/async#timesn-iterator-callback) or similar.

**Comment by dcousens** [comment]
`async.cargo` and `async.queue` are perfect for batching and maximising parallel connections.

**Comment by MaxSchumacher** [comment]
Thanks so much, I've finally been able to implement it with async.cargo:
```
let q = async.queue((transactions, callback) => {
    getrawtransaction(transactions)
        .then(fetchAndCalculateTransactioncosts)
        .then(result => {
            fs.appendFile("FullYear2015.csv",
                `${result[0]}` + ", " +
                `${result[1]}` + ", " +
                `${result[1]-result[2]}` +"\n"
            );
            callback();
        }
    );
}, 20);

const getBlockRange = (start, end) => {
    for (let height = start; height <= end; height++) {

        //Taking a sample of 6 blocks per day (144/24)
        if (height % 24 == 0) {
            fetchBlockHashes(height)
                .then(fetchBlocks)
                .then(getTransactionHashes)
                .then(transactionHashes => {
                    for (let transactions of transactionHashes) {
                        q.push(transactions, function (err) {
                            if (err) throw err;
                        });
                    }
                })
        }
    }
};
```

**Comment by dcousens** [comment]
I personally found the error callbacks for this library difficult to handle, so if you want a generalized solution using `cargo` and `queue`, see below:

``` javascript
let async = require('async')
let Yajrpc = require('yajrpc')

let client = new Yajrpc({
  url: 'http://localhost:8332',
  user: process.env.RPCUSER,
  pass: process.env.RPCPASSWORD
})

// process RPCCONCURRENT payloads concurrently
let queue = async.queue(({ payload }, callback) => {
  client.batch(payload, callback)
}, process.env.RPCCONCURRENT)

// group RPC calls into payloads of RPCBATCHSIZE
let cargo = async.cargo((payload, callback) => {
  queue.push({ payload }, callback)
}, process.env.RPCBATCHSIZE)

module.exports = function rpc (method, params, callback) {
  cargo.push({
    method,
    params,
    callback
  })
}
```

It uses my own library [`yajrpc`](https://github.com/dcousens/yajrpc),  and can be used like so:

``` javascript
rpc('getrawtransaction', ['f09a5a86a49eee276c2db6875c8416e19b2762b98da43dc6eec210d8b6f8ca85'], function (err, result) {

})
```

The transport is batched into `RPCCONCURRENT` RPC calls, which have a batch size of `RPCBATCHSIZE` each.
Means you can do many, large, concurrent requests to the RPC without killing it,  while still having a sane API for error handling.
