### ISSUE TITLE
Support authentication cookie

### ISSUE THREAD

**Issue by markasoftware** [freewil/node-bitcoin#37]
The current "recommended" way to authenticate to the daemon is using the on-disk authentication cookie, while this module seems only to support username + password.

**Comment by ruimarinho** [comment]
@markasoftware it's one possible solution but it requires the cli (which fires the rpc request) and the daemon to be on the same machine. The proper rpc authentication mechanism (rpcauth) provides remote access and the same security guarantees as the cookie-based one. You can read more about this [here](https://github.com/ruimarinho/docker-bitcoin-core#using-rpcauth-for-remote-authentication).
